### ISSUE TITLE
Error in scan.py

### ISSUE THREAD

**Issue by dipendrachaudhary** [Alpacked/terraform-clamav-s3#1]
Getting this error in scan.py when looked from cloudwatch logs
`Traceback (most recent call last):
  File "/var/task/scan.py", line 236, in lambda_handler
    scan_result, scan_signature = clamav.scan_file(file_path)
  File "/var/task/clamav.py", line 212, in scan_file
    raise Exception(msg)`

**Comment by iumikhailov** [comment]
Hello.
This error appears when there are no clamav definitions in the bucket.
Wait until Lambda function downloads definitions and then you can test - upload files to your bucket.
